### ISSUE TITLE
Integrate cjklib library to handle Chinese

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#21]
Consider incorporating python library for Chinese: http://code.google.com/p/cjklib/
    - would give Cantonese, IPA, Gwoyeu (partial Wade-Giles) and a ton of other functionality

**Comment by Nick3C** [comment]
This looks good, does a lot of the things we do and things we want. However, it does seem like the project is still too immature (release Nov 2008). We should keep an eye on it and check back again in 2010.

**Comment by batterseapower** [comment]
I've been working on integrating this in my local branch (not pushed yet). I'm not using much of the code yet except the database builder, but by integrating it we have that option and can start replacing some of our code with cjklib stuff (in particular the pinyin tokenization is a candidate).

The resulting toolkit is blazing fast - no load delay due to using SQLite.

The one problem is that we need a first-run wizard which generates the database, because its too big to distribute in the ZIP (88MB).

**Comment by batterseapower** [comment]
By the way, by distributing just the essential dictionaries, trimming out everything except kMandarin from Unihan, and distributing the dictionaries in a ZIP (it doesn't matter to the dictionary builder) we can reduce the size of the dictionaries to just 6MB. Thats a much better download size!

**Comment by Nick3C** [comment]
Ah that is really wicked. I saw that you were working towards these changes in the git uploads. I can't wait to see it, but the coding for that is most definitely beyond me :)

I think it is actually a good thing that the database is build on the fly. It lends itself to allowing the auto-update of the dictionary and means that I don't need to do the database updating for each release (which is nice). By the way, for some unknown reason both handedict and cfdict has shrunk substantially in the last 3 months, not entirely sure why.

Our long-term solution is starting to become clear: a setup wizard that generates the database and then walks the user through setting up the deck for the first time. That way we could actually add the fields automatically and suggest template

The whole plugin package is already uploaded to the anki server as a zip by the way.

**Comment by batterseapower** [comment]
It's almost there, I'm getting some REALLY BAD crash bugs in my first run wizard that I think are caused by bugs in PyQT4. I need to find a workaround.

Yes, this does fit in nicely with our first-run wizard story. I've set it up so that if any of the dictionaries timestamps have changed since the last database build, the DB will be automatically rebuilt when you restart Anki. It can also handle updating the dictionary from the .zip you download from the web directly. This is a first step towards auto-update.

You do not need to rebuild the database if you just edit your user dictionary: there is a seperate code path for that.

I forgot that the plugin was zipped :-) zipping a zip is unlkely to make a difference, but at least we can still benefit from trimming Unihan.

**Comment by batterseapower** [comment]
I've merged these changes into my branch. The PyQT4 thing was really hard to track down (and I found even more weirdness afterwards).

It's very likely that I've broken the toolkit on Windows. Give me a shout if so :-). I'll also run my own test.

**Comment by batterseapower** [comment]
It seems to work OK on my Mac laptop too, but you need to run these two commands after pulling:

```
git submodule init
git submodule update
```

**Comment by Nick3C** [comment]
Two bugs:

One on load:
Traceback (most recent call last):
  File "ankiqt\ui\main.pyc", line 2401, in loadPlugins
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\Pinyin Toolkit.py", line 47, in 
AttributeError: 'PinyinToolkit' object has no attribute 'installhooks'

Another one when opening preferences:

  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 136, in triggered
    controller = pinyin.forms.preferencescontroller.PreferencesController(preferences, self.notifier, self.mediamanager, self.config)
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\forms\preferencescontroller.py", line 41, in **init**
    self.updaterfromexpr = pinyin.updater.FieldUpdaterFromExpression(pinyin.mocks.NullNotifier(), pinyin.mocks.MockMediaManager(previewmedia), self.model)
TypeError: **init**() takes exactly 5 arguments (4 given)

It also seems to be a similar speed for filling...

**Comment by batterseapower** [comment]
Err.. are you sure those files are up to date? I'm absolutely sure that that code has already changed.

RE speed: yes it is disappointingly slow on my laptop (slower than the last version, actually). It just looked faster to me because I don't notice the filling delay on my big desktop, and we HAVE removed the loading delay almost entirely.

I actually sat down just this minute to look into how we can tune the database to make it work better. Sqlite CAN be very very fast, so I'm sure this is fixable.

**Comment by Nick3C** [comment]
it was yesterday's code. I updated then but didnt pull again this evening.

The second bug remains with the latest code (preferences):

Exception exceptions.AttributeError: "'PreferencesController' object has no attribute 'mappings'" in > ignored
Traceback (most recent call last):
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 155, in 
    self.mw.connect(self.action, QtCore.SIGNAL('triggered()'), lambda: self.triggered())
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 136, in triggered
    controller = pinyin.forms.preferencescontroller.PreferencesController(preferences, self.notifier, self.mediamanager, self.config)
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\forms\preferencescontroller.py", line 41, in **init**
    self.updaterfromexpr = pinyin.updater.FieldUpdaterFromExpression(pinyin.mocks.NullNotifier(), pinyin.mocks.MockMediaManager(previewmedia), self.model)
TypeError: **init**() takes exactly 5 arguments (4 given)

**Comment by batterseapower** [comment]
I really think you haven't updated properly. My updater.py contains this:

```
class FieldUpdaterFromExpression(object):
    def __init__(self, notifier, mediamanager, config, database):
```

I don't think yours does - or at least, thats what the error seems to say. If your updater.py DOES look like that, then try removing all the .pyc files in the directory.

**Comment by batterseapower** [comment]
No, wait I'm talking shit. Apologies for doubting you :-)

**Comment by Nick3C** [comment]
no worries. I did double check it all. it exists, .pyc wasnt the prob.

**Comment by batterseapower** [comment]
Right, I've fixed that bug and I've also changed the database generation. It turns out that if you turn off the use of FTS3 then queries can get 4 times faster. It's still a bit slower than I'd like though.

To get this working, after the pull do a "git submodule update" again (I've had to change cjklib) .You will also need to delete your pinyin/db/cjklib.db to force the toolkit to regenerate it without FTS3 turned on.

Let me know how it goes.

**Comment by batterseapower** [comment]
Testing the new database settings on my laptop, it is much faster. I think about 40% of the remaining delay is due to the database and 60% due to the file copy speed of the audio. Your suggestion of hash precomputation might be a nice idea to pursue to reduce that copy speed a bit...

**Comment by Nick3C** [comment]
yes, much faster for me too. As you say, not quite there, but it has lost the feeling of extreme sluggishness.

**Comment by Nick3C** [comment]
Mass fill still isn't very happy...

An error occurred in a plugin. Please contact the plugin author.

Traceback (most recent call last):
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 180, in 
    self.mw.connect(self.action, QtCore.SIGNAL('triggered()'), lambda: self.mw.deck is not None and self.triggered())
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 194, in triggered
    getattr(self.updaters[field], self.**class**.updatehow)(factproxy, factproxy[field])
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updater.py", line 283, in updatefact
    dictreading = self.getdictreading(expression)
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updater.py", line 248, in getdictreading
    dictreading = lookup()
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updater.py", line 243, in 
    lambda: self.dictionary.reading(expression)
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\dictionary.py", line 112, in reading
    return self.mapparsedtokens(sentence, addword)
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\dictionary.py", line 138, in mapparsedtokens
    addword(words, text, tokenizespaceseperated(readingsmeanings[0][0]))
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\model.py", line 256, in tokenizespaceseperated
    return [tokenizeone(possible_token, forcenumeric=True) for possible_token in text.split()]
AttributeError: 'tuple' object has no attribute 'split'

**Comment by batterseapower** [comment]
I can't reproduce your problem, but I _think_ I know what caused it: the presence of a character not in CEDICT, but in Unihan, in your deck. I've pushed a fix.

**Comment by batterseapower** [comment]
In the process of fixing #121, I spotted a HUGE performance bug in what I was doing. I've doubled the speed of my testsuite by fixing it, and the speed boost in Anki itself is even better. I think the only remaining delay is from sound copying!

**Comment by Nick3C** [comment]
good, it's operating much faster for me too now.

**Comment by batterseapower** [comment]
Great. II'll close the ticket then - the cjklib integration seems to be basically OK now.
